version: '3.9'

services:
  medical-chatbot:
    build: .
    container_name: medical-chatbot
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
